WIP Feat/user event log
commons-stack/praise pull request #365
Opened 2022-05-05 20:53 UTC by mattyg

Resolves #309 

**Overview**
- new api endpoint `/api/eventlogs/all`
- helper utility `logEvent()`
- tests on api endpoint & helper utility

**Todo**
- Frontend for viewing list of events, paginated

2022-05-12 12:25 UTC, kristoferlund requested changes
Looks great!! ✨

One additional action we should log is:
- Remove role from user

For the layout, in general we should try keep it as close to the other pages as possible. These are my proposed changes: 

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/9698363/168074050-8d75d708-f654-45f5-b2d1-a7206ed808b3.png">

2022-05-14 19:27 UTC, mattyg commented
> * Remove role from user
done

> For the layout, in general we should try keep it as close to the other pages as possible. These are my proposed changes:
done

With this UX change, there will likely be bugs related to the displayed user name (until we implement #361 and refactor out the confusion around users and useraccounts). Currently, some actions are taken by useraccounts, while others are taken by users. Thus the eventlog model stores the user and / or the useraccount id. Thus we need to conditionally determine the user name to display on the event log based on the data available within it.

Also I just wanted to make sure you saw this note from the comment above:

> **Also, just a note that currently makes individual quantification scores public, before the quantification period is closed.** Perhaps it should be modified to only include quantification user events after the related period is closed.

2022-05-16 09:37 UTC, kristoferlund requested changes
Looks great!

The only thing I noticed is that the "← Previous" page link don't appear.

> Currently, some actions are taken by useraccounts (sometimes without an associated user), while others are taken by users. Thus the eventlog model has to store both the user id and / or the useraccount id. Thus we need to conditionally determine the user name to display based on the data available within each individual event log.

Yes. We need to clear this up and decide on a model that is more sustainable. Let's continue discussion in #361.

> Also, just a note that currently makes individual quantification scores public, before the quantification period is closed. Perhaps it should be modified to only include quantification user events after the related period is closed.

Sounds like a good idea. If I remember correctly the rule is this: 
- Admins can see everything
- Users and Quantifiers can only see scores after period has been closed

2022-05-17 20:59 UTC, mattyg commented
> The only thing I noticed is that the "← Previous" page link don't appear.

Fixed 

> > Also, just a note that currently makes individual quantification scores public, before the quantification period is closed. Perhaps it should be modified to only include quantification user events after the related period is closed.
> 
> Sounds like a good idea. If I remember correctly the rule is this:
> 
> * Admins can see everything
> * Users and Quantifiers can only see scores after period has been closed

Done. Quantification event logs for an active period are still included, but their description is obscured by a Notice that says "Praise scores are not visible during quantification" (the same notice as in the PeriodDetailPage).

I think it makes sense to include them with a notice hiding the details rather than to exclude them entirely. But let me know what you think:

![Screenshot_2022-05-17_16-53-52](https://user-images.githubusercontent.com/159270/168908987-78a08514-64ea-4e3e-82f5-82d78cea52e5.png)

2022-05-18 09:25 UTC, kristoferlund approved these changes
Looks great!

2022-05-18 09:25 UTC, kristoferlund commented on packages/api/src/user/utils.ts
> +export const generateUserName = async (user: UserDocument): Promise<string> => {
Nice, like we talked about, attempting to establish a single source of truth for every business rule. And to push it as far up the "tree" as possible with the database representing the "root node".

2022-05-18 09:26 UTC, merged