Feat/317/verbose /admin announce summary
commons-stack/praise pull request #441
Opened 2022-06-03 22:42 UTC by Vyvy-vi

Resolves #317 

This PR adds a summary report file that is sent when the /admin announce command is used. We might need to refactor this a bit in future and use the praise username instead of discord ids.

![Screenshot 2022-06-04 at 12 27 33 AM](https://user-images.githubusercontent.com/62864373/171963383-dabc4f6c-11aa-4665-9621-5ae73f8a5bb3.png)
![Screenshot 2022-06-04 at 12 27 49 AM](https://user-images.githubusercontent.com/62864373/171963386-cd6d7452-a513-4a11-ba50-713734801fea.png)

2022-06-05 21:50 UTC, mattyg commented on packages/discord-bot/src/utils/dmTargets.ts
> +  let summary = `User\t\t\t\tStatus\n`;
lint warning

2022-06-05 21:52 UTC, mattyg requested changes
Awesome!

I think we need to replace the discord ids with user names before it effectively resolves #317.

2022-06-07 22:40 UTC, Vyvy-vi commented
> I think we need to replace the discord ids with user names before it effectively resolves #317.
This can be resolved when #377 is implemented. We can't use discord usernames if the user isn't present in the discord.
One temp. solution may be to fetch all the `UserAccount`s associated with the `User` and to return a more detailed output -

| User | DiscordUsername | TelegramUsername | Status | Reason |
| :-: | :-: | :-: | :-: | :-: |
| A | A_on_discord_old_account | A_on_Telegram | Undelivered | User Not Found in discord |
| B | B_on_discord | B_on_Telegram | Delivered | - | 
| C | C_on_discord | C_on_Telegram | Undelivered | Can't DM User | 

Would this add a significant overhead to the process? 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-08 07:40 UTC, kristoferlund commented
> This can be resolved when #377 is implemented. We can't use discord usernames if the user isn't present in the discord.

How could the user not be on Discord? In order to be a quantifier you need to activate your account, linking `UserAccount` to `User`.

2022-06-08 10:29 UTC, Vyvy-vi commented
> How could the user not be on Discord? In order to be a quantifier, you need to activate your account, linking `UserAccount` to `User`.

People can leave the discord server after activating, or they can be kicked/banned for some reason, or their discord account might have been deleted.

2022-06-09 10:13 UTC, Vyvy-vi commented
That's true. It might add some extra API calls, but we can add that 👍 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-10 19:35 UTC, Vyvy-vi commented
The code isn't as DRY as I'd like, however, I think we can work on that when we make a separate function for tabularisation (or if we opt to use a CSV file, instead).

Here's the new version -
![Screenshot 2022-06-11 at 12 59 17 AM](https://user-images.githubusercontent.com/62864373/173137157-5e594f12-cad6-41d4-aa2c-a6ff3d90f6c5.png)
![Screenshot 2022-06-11 at 12 58 57 AM](https://user-images.githubusercontent.com/62864373/173137159-cfc7acf0-3243-487e-b67b-31578ff0e9db.png)

2022-06-10 19:48 UTC, Vyvy-vi commented
also, how to type this properly? -
```
interface FailedToDmUsersList {
  invalidUsers: string[];
  notFoundUsers: string[];
  closedDmUsers: string[];
  unknownErrorUsers: string[];
}

const failed: FailedToDmUsersList = {
  invalidUsers: <string[]>[],
  notFoundUsers: <string[]>[],
  closedDmUsers: <string[]>[],
  unknownErrorUsers: <string[]>[]
};
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-12 19:30 UTC, mattyg commented
> also, how to type this properly? -

Since you already defined it in the interface, you can just create an object that implements it. The type `string[]` allows for an empty array (as long as any items you subsequently add to it are strings). So like this:

```
interface FailedToDmUsersList {
  invalidUsers: string[];
  notFoundUsers: string[];
  closedDmUsers: string[];
  unknownErrorUsers: string[];
}

const failed: FailedToDmUsersList = {
  invalidUsers: [],
  notFoundUsers: [],
  closedDmUsers: [],
  unknownErrorUsers: []
};
```

2022-06-12 19:30 UTC, mattyg approved these changes
awesome!

2022-06-15 07:47 UTC, kristoferlund approved these changes
Looks great @Vyvy-vi! I made two small text changes. Now merging.

2022-06-15 07:47 UTC, merged