WIP: Organise settings interface #586
commons-stack/praise pull request #631
Opened 2022-10-10 16:22 UTC by nebs-dev

Resolves #586 

- migration for the new settings field `section`
- modified types and transformer
- created separate components for each setting group

2022-10-10 16:24 UTC, nebs-dev commented
@kristoferlund can you take a look at this? 
I separated each setting group into components. I know components are almost the same but i though it is more clean this way and also maybe sometimes in future we would like to modify these screens more
Also i added DB field because maybe we will add option to move fields from one section into other and than we only need to change this new `section` value

2022-10-11 07:15 UTC, kristoferlund requested changes
Nice!

I agree with breaking out each settings group into components, looks good! 

Made some small styling comments.

One thing I think you should change though. We use the term `group` and `SettingsGroup`. `section` is very closely related to the groups, I think `subgroup` would more clearly show the connection.

2022-10-11 07:15 UTC, kristoferlund commented on packages/frontend/src/pages/Settings/components/SettingsSection.tsx
> +      <div className="mb-8">
Margin 5 is the "default" margin we use in most places.

2022-10-11 07:15 UTC, kristoferlund commented on packages/frontend/src/pages/Settings/components/SettingsSection.tsx
> +        <div className="mb-2 text-xl">{header}</div>
Use `<h2>`

2022-10-17 06:59 UTC, kristoferlund approved these changes
Nice Nebs! Merging!

2022-10-17 06:59 UTC, merged